# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param tcl.collectionResultDisplayLimit 0
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/irfan/Vivado/pinpon3/pinpon3.cache/wt [current_project]
set_property parent.project_path /home/irfan/Vivado/pinpon3/pinpon3.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths {
  /home/irfan/Vivado/xilinx-ip-repo
  /home/irfan/Vivado/Obj_Buffer/Obj_Buffer.srcs/sources_1/new
} [current_project]
set_property ip_output_repo /home/irfan/Vivado/pinpon3/pinpon3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
add_files /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/bd_48ac_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_34/bd_48ac_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/bd_48ac_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_36/bd_48ac_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_37/bd_48ac_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_38/bd_48ac_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_bram_0/design_1_axi_bram_ctrl_0_bram_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/bd_f60c_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/bd_f60c_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/irfan/Vivado/pinpon3/pinpon3.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/irfan/Vivado/pinpon3/pinpon3.srcs/constrs_1/imports/Vivado/pynq-z2.xdc
set_property used_in_implementation false [get_files /home/irfan/Vivado/pinpon3/pinpon3.srcs/constrs_1/imports/Vivado/pynq-z2.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
