vlib work
vlib riviera

vlib riviera/xilinx_vip
vlib riviera/xil_defaultlib
vlib riviera/xpm
vlib riviera/axi_lite_ipif_v3_0_4
vlib riviera/lib_cdc_v1_0_2
vlib riviera/interrupt_control_v3_1_4
vlib riviera/axi_gpio_v2_0_19
vlib riviera/proc_sys_reset_v5_0_12
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/smartconnect_v1_0
vlib riviera/axi_protocol_checker_v2_0_3
vlib riviera/axi_vip_v1_1_3
vlib riviera/processing_system7_vip_v1_0_5
vlib riviera/xlconstant_v1_1_5
vlib riviera/blk_mem_gen_v8_3_6
vlib riviera/axi_bram_ctrl_v4_0_14
vlib riviera/blk_mem_gen_v8_4_1

vmap xilinx_vip riviera/xilinx_vip
vmap xil_defaultlib riviera/xil_defaultlib
vmap xpm riviera/xpm
vmap axi_lite_ipif_v3_0_4 riviera/axi_lite_ipif_v3_0_4
vmap lib_cdc_v1_0_2 riviera/lib_cdc_v1_0_2
vmap interrupt_control_v3_1_4 riviera/interrupt_control_v3_1_4
vmap axi_gpio_v2_0_19 riviera/axi_gpio_v2_0_19
vmap proc_sys_reset_v5_0_12 riviera/proc_sys_reset_v5_0_12
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_protocol_checker_v2_0_3 riviera/axi_protocol_checker_v2_0_3
vmap axi_vip_v1_1_3 riviera/axi_vip_v1_1_3
vmap processing_system7_vip_v1_0_5 riviera/processing_system7_vip_v1_0_5
vmap xlconstant_v1_1_5 riviera/xlconstant_v1_1_5
vmap blk_mem_gen_v8_3_6 riviera/blk_mem_gen_v8_3_6
vmap axi_bram_ctrl_v4_0_14 riviera/axi_bram_ctrl_v4_0_14
vmap blk_mem_gen_v8_4_1 riviera/blk_mem_gen_v8_4_1

vlog -work xilinx_vip  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93 \
"/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \

vcom -work axi_lite_ipif_v3_0_4 -93 \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work lib_cdc_v1_0_2 -93 \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work interrupt_control_v3_1_4 -93 \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \

vcom -work axi_gpio_v2_0_19 -93 \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/c193/hdl/axi_gpio_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_axi_gpio_0_0/sim/design_1_axi_gpio_0_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
"../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \

vcom -work proc_sys_reset_v5_0_12 -93 \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_proc_sys_reset_0_0/sim/design_1_proc_sys_reset_0_0.vhd" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -work axi_protocol_checker_v2_0_3  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/03a9/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \

vlog -work axi_vip_v1_1_3  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b9a8/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_5  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \
"../../../bd/design_1/ip/design_1_rgb2tmds_0_0/design_1_rgb2tmds_0_0_sim_netlist.v" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/sim/bd_48ac.v" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5160/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_48ac_s00a2s_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/acc2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_48ac_m01s2a_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/sim/bd_48ac_m02s2a_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/28cb/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_39/sim/bd_48ac_m02e_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_34/sim/bd_48ac_m02arn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/sim/bd_48ac_m02rn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_36/sim/bd_48ac_m02awn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_37/sim/bd_48ac_m02wn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_38/sim/bd_48ac_m02bn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/sim/bd_48ac_m01e_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_48ac_m01arn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_48ac_m01rn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_48ac_m01awn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_48ac_m01wn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_48ac_m01bn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_48ac_sarn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_48ac_srn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_48ac_sawn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_48ac_swn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_48ac_sbn_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/afa8/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_48ac_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/4521/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_48ac_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/d1fc/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_48ac_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/4e7b/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_48ac_arinsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_48ac_rinsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_48ac_awinsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_48ac_winsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_48ac_binsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_48ac_aroutsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_48ac_routsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_48ac_awoutsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_48ac_woutsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_48ac_boutsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_48ac_arni_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_48ac_rni_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_48ac_awni_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_48ac_wni_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_48ac_bni_0.sv" \

vlog -work xlconstant_v1_1_5  -v2k5 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_48ac_one_0.v" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_48ac_psr_aclk_0.vhd" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/sim/design_1_smartconnect_0_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_vtg_0_0/design_1_vtg_0_0_sim_netlist.v" \

vlog -work blk_mem_gen_v8_3_6  -v2k5 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/2751/simulation/blk_mem_gen_v8_3.v" \

vcom -work axi_bram_ctrl_v4_0_14 -93 \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6db1/hdl/axi_bram_ctrl_v4_0_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_axi_bram_ctrl_0_0/sim/design_1_axi_bram_ctrl_0_0.vhd" \
"../../../bd/design_1/ip/design_1_rst_ps7_0_100M_0/sim/design_1_rst_ps7_0_100M_0.vhd" \

vlog -work blk_mem_gen_v8_4_1  -v2k5 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/b65a" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/70fd/hdl" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0a8d/hdl/verilog" "+incdir+../../../../pinpon3.srcs/sources_1/bd/design_1/ipshared/0000/hdl/verilog" "+incdir+/mnt/hafiz/PROGRAMLAR/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_bram_ctrl_0_bram_0/sim/design_1_axi_bram_ctrl_0_bram_0.v" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/sim/bd_f60c.vhd" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/sim/bd_f60c_ila_lib_0.vhd" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/sim/design_1_system_ila_0_0.vhd" \
"../../../bd/design_1/ipshared/bd5e/obj_buffer.vhd" \
"../../../bd/design_1/ip/design_1_displaybuffer_0_0/sim/design_1_displaybuffer_0_0.vhd" \
"../../../bd/design_1/sim/design_1.vhd" \

vlog -work xil_defaultlib \
"glbl.v"

